### ISSUE TITLE
Github Actions Build

### ISSUE THREAD

**Issue by InitRoot** [Kevin-Robertson/InveighZero#2]
Working Git Actions build available on my fork. Possible build code that can be used:
```
name: Build Inveigh
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses:  warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore Inveigh.sln
 
    - name: Build App
      run: msbuild Inveigh.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Inveigh
        path: "D:/a/InveighZero/InveighZero/Inveigh/obj/Debug/"

```
